server:
  port: 8082

spring:
  application:
    name: aiuser-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos


feign:
  hystrix:
    enabled: false