#server:
#  port: 8081
#
#spring:
#  application:
#    name: hello-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        username: nacos
#        password: nacos

spring:
  profiles:
    active: dev
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - gateway